id: IE77CFEC9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T17:13:51+00:00'
last_modified: '2022-06-08T01:18:26.379430+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN8060
  title: གསུང་འབུམ། སྒམ་པོ་པའི་གདན་རབས་རིམ་བྱོན།（1-5）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    94F7:
      image_group_id: I3CN8062
      title: ''
      total_pages: 350
      order: 1
      base_file: 94F7.txt
    A86E:
      image_group_id: I3CN8063
      title: ''
      total_pages: 376
      order: 2
      base_file: A86E.txt
    F5A7:
      image_group_id: I3CN8064
      title: ''
      total_pages: 332
      order: 3
      base_file: F5A7.txt
    2FE6:
      image_group_id: I3CN8065
      title: ''
      total_pages: 332
      order: 4
      base_file: 2FE6.txt
    B322:
      image_group_id: I3CN8066
      title: ''
      total_pages: 470
      order: 5
      base_file: B322.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
